CI workflow now automatically updates OpenAPI json and uploads in a file in backendfolder

diff --git a/.github/workflows/openapi-gen.yml b/.github/workflows/openapi-gen.yml
--- a/.github/workflows/openapi-gen.yml
+++ b/.github/workflows/openapi-gen.yml
@@ -10,17 +10,35 @@ on:
 jobs:
   generate-openapi:
     runs-on: ubuntu-latest
+
     steps:
       - uses: actions/checkout@v4
         
       # Generate OpenAPI definition
       - name: Generate OpenAPI Definition
         run: |
-          curl -fSL https://production-backend-container.whitehill-62ea132a.swedencentral.azurecontainerapps.io/apispec_1.json -o openapi.json
+          curl https://production-backend-container.whitehill-62ea132a.swedencentral.azurecontainerapps.io/apispec_1.json -o backend/openapi.json
 
-      # Upload the OpenAPI definition as an artifact
-      - name: Upload OpenAPI Definition
-        uses: actions/upload-artifact@v3
-        with:
-          name: openapi-definition
-          path: openapi.json
+      # Check for changes in the OpenAPI definition
+      - name: Check for Changes
+        run: |
+          # Check for differences in the OpenAPI JSON file
+          git diff --exit-code backend/openapi.json
+          
+          # Check exit code of the last command
+          if [[ $? -ne 0 ]]; then
+            echo "Changes detected."
+          else
+            echo "No changes detected."
+            exit 0  # Exit the job early if no changes
+          fi
+
+      # Commit and push the updated OpenAPI definition only if there are changes
+      - name: Commit and Push Changes
+        run: |
+          echo "Committing and pushing changes."
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add backend/openapi.json
+          git commit -m "Update OpenAPI definition"
+          git push
